---
- name: Install Required System Utilities
  hosts: localhost
  become: true
  become_method: sudo

  vars:
    ansible_python_interpreter: /usr/bin/python3
    SHELL: /bin/bash

  roles:
    - deno
    - sqlite
    - pgloader
    - just
    - datamash

