- name: Install deno install dependencies.
  apt:
    pkg: [ 'curl' , 'unzip' ]

- name: Run install.sh script.
  shell: curl -fsSL https://deno.land/x/install/install.sh | sudo DENO_INSTALL=/usr/local sh

- name: Install sqlite 
  apt: pkg=sqlite state=present update_cache=true

- name: Install pgloader
  apt: pkg=pgloader state=present update_cache=true

- name: Delete Just binary file if it already exists
  file:
    path: /usr/local/bin/just
    state: absent

- name: Install Just command
  shell: curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | sudo bash -s -- --to /usr/local/bin
  args:
    warn: false
