interpolateShebangContent := "../../interpolate-shebang-content.pl"
supplyRecipeJustFile := "../../recipe-suppliers.justfile"

_pg-dcp-recipe +ARGS:
    @just -f {{supplyRecipeJustFile}} {{ARGS}}

# Generate psql SQL snippets to build HTTP Client GraphQL objects
psql-construct-graphql:
    @cat graphql.sql

# Generate psql SQL snippets to drop HTTP Client GraphQL objects
psql-destroy-graphql:
    #!/usr/bin/env {{interpolateShebangContent}}    
    call destroy_http_client_graphql();
    DROP PROCEDURE IF EXISTS destroy_http_client_graphql();

# Generate psql SQL snippets to build HTTP Client objects
psql-construct-http:
    @cat http.sql

# Generate psql SQL snippets to drop HTTP Client objects
psql-destroy-http:
    #!/usr/bin/env {{interpolateShebangContent}}
    call destroy_http_client();
    DROP PROCEDURE IF EXISTS destroy_http_client();

# Generate complete psql SQL to build all library objects
psql-construct: psql-construct-http psql-construct-graphql

# Generate complete psql SQL to drop  all library objects
psql-destroy: psql-destroy-http psql-destroy-graphql
