- name: Ensure database {{ Calendso_Database }} is created
  become_user: postgres
  become: yes
  postgresql_db: name={{ Calendso_Database }}
             encoding='UTF-8'
             lc_collate='en_US.UTF-8'
             lc_ctype='en_US.UTF-8'
             template='template0'
             state=present
