---
- name: Install pgsql-http dependency modules
  apt: pkg=libcurl4-openssl-dev state=present update_cache=true

- name: Clone pgsql-http from GitHub
  git:
    repo: https://github.com/pramsey/pgsql-http.git
    dest: /tmp/pgsql-http

- name: pgsql-http Make clean 
  make:
    chdir: /tmp/pgsql-http
    target: clean
  
- name: Install pgsql-http (Make install)
  make:
    chdir: /tmp/pgsql-http
    target: install
