---
- name: Add pgaudit, pg_cron as shared_preload_libraries parameter in posgresql.conf
  shell: echo "shared_preload_libraries = 'pg_stat_statements, pgaudit, pg_cron, timescaledb'" >> {{ Postgres_Config_Path }}/postgresql.conf
